
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// For more information on how to use this file, see the Firebase documentation:
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// This is a public configuration and is safe to expose to the client.
export const firebaseConfig = {"apiKey":"your-api-key","authDomain":"your-auth-domain","projectId":"your-project-id","storageBucket":"your-storage-bucket","messagingSenderId":"your-messaging-sender-id","appId":"your-app-id"};
