
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// For more information on how to use this file, see the Firebase documentation:
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// This is a public configuration and is safe to expose to the client.
export const firebaseConfig = {"apiKey":"mock-api-key","authDomain":"mock-auth-domain","projectId":"mock-project-id","storageBucket":"mock-storage-bucket","messagingSenderId":"mock-messaging-sender-id","appId":"mock-app-id"};
