
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// For more information on how to use this file, see the Firebase documentation:
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// This is a public configuration and is safe to expose to the client.
export const firebaseConfig = {"apiKey":"AIzaSyALP-faVqKOOsswJfpDzyhjF8Y8pFaX78I","authDomain":"badgerexchange-14885.firebaseapp.com","projectId":"badgerexchange-14885","storageBucket":"badgerexchange-14885.firebasestorage.app","messagingSenderId":"m541856699989","appId":"1:541856699989:web:493ed7e35de797d58226dc"};
